name: Publish to Raycast

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    environment:
      name: raycast-publish

    steps:
      - uses: maxchang3/raycast-extension-actions/publish@v1
        with:
          raycast_extensions_fork_full_name: maxchang3/raycast-extensions
          github_username: maxchang3
          extension_name: bangumi
          ignore_paths: |
            .vscode
            .github
            .claude
            .agents
            release-please-config.json
            .release-please-manifest.json
            skills-lock.json
          github_access_token: ${{ secrets.RAYCAST_EXTENSIONS_TOKEN }}
