name: Sync raycast/extension Changes

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: maxchang3/raycast-extension-actions/sync@v1
        with:
          extension_name: bangumi
          ignore_paths: |
            CHANGELOG.md
            .github/
          github_access_token: ${{ secrets.RAYCAST_EXTENSIONS_TOKEN }}
