name: Sync raycast/extension Changes

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: maxchang3/raycast-extension-actions/sync@v1
        with:
          extension_name: bangumi
          raycast_extensions_fork_full_name: maxchang3/raycast-extensions
          ignore_paths: |
            CHANGELOG.md
          github_access_token: ${{ secrets.RAYCAST_EXTENSIONS_TOKEN }}
